### ISSUE TITLE
Extension breaks Browserstack

### ISSUE THREAD

**Issue by flostellbrink** [samuelmaddock/metastream#186]
- Metastream Version: Extension: 0.1.12
- Browser + Version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
- OS Version: Windows 10 1903

Steps to Reproduce:

1. Install Metastream Extension in Chrome
2. Go to https://live.browserstack.com/
3. Start a session with any mobile device. (e.g. iphone xs, safari)
4. Open devtools

Devtools will open but be empty.
With the extension disabled, devtools work again.

I would guess that simply blacklisting browserstack should solve this problem.

**Comment by samuelmaddock** [comment]
😱 So sorry you had to figure this out. Thanks for reporting, I think I know what's happening.

Part of the extension [monkeypatches a function called `document.createElement`](https://github.com/samuelmaddock/metastream/blob/master/packages/metastream-remote-extension/src/first.js#L21-L31)  and I didn't know it accepted two arguments. BrowserStack's devtools make use of this and fails since I don't pass through the second argument.

I'll get this fixed in the next release, following the current pending release.

**Comment by flostellbrink** [comment]
Thanks for looking into it so quickly!
