### ISSUE TITLE
mega.nz non-embed link support

### ISSUE THREAD

**Issue by Roboyarou** [samuelmaddock/metastream#232]
Any Mega videos being played will result in playing a blank, grey screen.

Sample Video:
https://mega.nz/#!IxFiBKYb!EJ7_ob9njQAvuuqpaFsCeymAHeUzdULCj1lw1rapdkI

**Comment by samuelmaddock** [comment]
The video is failing to load due to a cross-origin security issue. I might be able to fix it in the Metastream Remote extension.

For now, a workaround is to use the embed URL accessible from the share modal.
![firefox_2019-12-07_19-07-12iC7f](https://user-images.githubusercontent.com/1656324/70382159-f6e5e500-1924-11ea-8ec2-23b2ce2e0c3d.png)

**Comment by Roboyarou** [comment]
I see. Thank you so much.

**Comment by samuelmaddock** [comment]
Not going to be able to provide a solution to this besides using the documented workaround.
