### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by RyuNeko** [samuelmaddock/metastream#260]
For some reason, websites like CrunchyRoll and Funimation won't work because the cookies isn't enabled. When I'm not on Metastream everything is fine but once I'm on it, those websites don't work.

**Comment by samuelmaddock** [comment]
Which browser and version are you using (please fill out the template next time 😭)? Some browsers block third-party cookies from loading. Since Metastream embeds other websites within itself, that'll prevent cookies from working.

Besides allowing third-party cookies in your browser, using the popup player can also work.
![chrome_2020-03-13_19-44-42Bajr](https://user-images.githubusercontent.com/1656324/76669672-1b281200-6563-11ea-9920-ecfed517b574.png)

**Comment by davidhaymond** [comment]
For those affected, here's how to re-enable third-party cookies in Google Chrome:

In your address bar, go to **chrome://flags/#same-site-by-default-cookies**, find the **SameSite by default cookies** setting, and set it to **Disabled**. Click **Restart** to restart your browser.

**Comment by samuelmaddock** [comment]
Should be fixed in the latest Chrome extension v0.4.2.
