### ISSUE TITLE
Hulu not loading

### ISSUE THREAD

**Issue by sleepyvulpini** [samuelmaddock/metastream#66]
- Metastream Version: this one
- OS Version:

Steps to Reproduce:

1. log in to hulu.com
2. it says unsupported browser
![fc288cdcef9d4be4aa4e8fbff4b533b0](https://user-images.githubusercontent.com/47405751/52384859-374aad00-2a4d-11e9-8cdd-b3076a9b9e17.png)

**Comment by samuelmaddock** [comment]
Behind the scenes Metastream is using an older version of the Chrome browser. When #1 is resolved, I'll be able to update to a newer version. Until then this might be a reoccurring issue.

I've added a change to fake the version of Chrome being used to get around this partially. Hulu URLs might need to be pasted into the chat instead of using the in-app browser unfortunately.

**Comment by samuelmaddock** [comment]
Closing as this will soon be fixed by #94.
